#+TITLE: Guix Notes
#+AUTHOR: librepup/nixpup
#+DESCRIPTION: Notes, Tips, and useful Information about GNU Guix
* Chapters
** Installation
*** Installation Process
**** Partitioning and System Init
***** (U)EFI
Basic (U)EFI Partition Layout and Creation Process:
****** Partition
If you want a swap partition, format and partition disks like this:
#+BEGIN_SRC sh
sudo parted /dev/sda --script \
     mklabel gpt \
     mkpart primary linux-swap 1MiB 4096MiB \
     name 1 guix-swap \
     mkpart ESP fat32 4096MiB 6144MiB \
     name 2 guix-efi \
     set 2 esp on \
     mkpart primary ext4 6144MiB 100% \
     name 3 guix-root

sudo mkswap -L guix-swap /de/sda1
sudo swapon /dev/sda1
sudo mkfs.fat -F32 -n guix-efi /dev/sda2
sudo mkfs.ext4 -L guix-root /dev/sda3
sudo mount /dev/sda3 /mnt
sudo mkdir -p /mnt/boot/efi
sudo mount /dev/sda2 /mnt/boot/efi
#+END_SRC

Otherwise, partition like this:
#+BEGIN_SRC sh
sudo parted /dev/sda --script \
  mklabel gpt \
  mkpart ESP fat32 1MiB 2048MiB \
  name 1 guix-efi \
  set 1 esp on \
  mkpart primary ext4 2048MiB 100% \
  name 2 guix-root

sudo mkfs.fat -F32 -n guix-efi /dev/sda1
sudo mkfs.ext4 -L guix-root /dev/sda2
sudo mount /dev/sda2 /mnt
sudo mkdir -p /mnt/boot/efi
sudo mount /dev/sda1 /mnt/boot/efi
#+END_SRC
****** Bootloader and Filesystem Configuration for (U)EFI Setup
#+BEGIN_SRC guile
(bootloader (bootloader-configuration
  (bootloader grub-efi-bootloader)
  (targets '("/boot/efi"))
  (keyboard-layout keyboard-layout)))

(file-systems (cons* (file-system
                      (device (file-system-label "guix-root"))
                      (mount-point "/")
                      (type "ext4"))
                     (file-system
                      (device (file-system-label "guix-efi"))
                      (mount-point "/boot/efi")
                      (type "vfat"))
                     %base-file-systems))

;; If you enabled Swap, add this:
(swap-devices (list
               (swap-space
                (target (file-system-label "guix-swap")))))
#+END_SRC

***** Legacy/BIOS
Basic Legacy/BIOS Partition Layout anc Creation Process:
****** Partition and Mount
#+BEGIN_SRC sh
sudo parted /dev/sda --script \
  mklabel msdos \
  mkpart primary ext4 1MiB 100% \
  set 1 boot on

sudo mkfs.ext4 -L guix-root /dev/sda1
sudo mount /dev/sda1 /mnt
#+END_SRC

If you want a swap partition, do this instead:
#+BEGIN_SRC sh
sudo parted /dev/sda -- script \
     mklabel msdos \
     mkpart primary linux-swap 1MiB 4096MiB \
     mkpart primary ext4 4096MiB 100% \
     set 2 boot on


sudo mkswap -L guix-swap /dev/sda1
sudo swapon /dev/sda1
sudo mkfs.ext4 -L guix-root /dev/sda2
sudo mount /dev/sda2 /mnt
#+END_SRC

****** Bootloader and Filesystem
#+BEGIN_SRC guile
(bootloader (bootloader-configuration
              (bootloader grub-bootloader)
              (keyboard-layout keyboard-layout)
              (targets '("/dev/sdb")))) ; or other '/dev/sdX'-drive with root partition.

(file-systems (cons* (file-system
                       (mount-point "/")
                       (device (file-system-label "guix-root"))
                       (type "ext4")) %base-file-systems))

;; If you enabled Swap, add this:
(swap-devices (list
               (swap-space
                (target (file-system-label "guix-swap")))))
#+END_SRC

***** System Initialization
To initialize the Guix System, run `guix system init /path/to/config.scm /mnt`, e.g.:
#+BEGIN_SRC sh
mkdir -p /mnt/etc/guix
mv /path/to/geex/* /mnt/etc/guix/
guix system init /mnt/etc/guix/config.scm /mnt
#+END_SRC

****** Cow-Store
This is an old/outdated command you had to run pre-2020 Guix System:
#+BEGIN_SRC sh
herd start cow-store /mnt
#+END_SRC

***** Passwords
Set passwords for users inside the "/mnt"-mounted GNU+Linux install.
#+BEGIN_SRC sh
passwd -R /mnt root
passwd -R /mnt puppy
#+END_SRC

**** Channel Setup
Authorize channel keys via 'sudo guix archive --authorize < /etc/guix/files/keys/nonguix.pub'.
#+BEGIN_SRC sh
guix shell git-minimal
git clone https://github.com/librepup/geex.git
mkdir -p /mnt/geex
mkdir -p ~/.config/guix
cp ./geex/channels.scm ~/.config/guix/channels.scm
guix archive --authorize < ./geex/files/keys/nonguix.pub
; Optional, define channels file: 'guix pull --channels=/path/to/channels.scm'
guix pull
#+END_SRC

*** Wifi Configuration
**** Commands
Find WiFi Device/Cards Name via 'ifconfig -a'.
#+BEGIN_SRC sh
rfkill unblock all
wpa_supplicant -c wifi.conf -i interface1s0 -B
dhclient -v interface1s0
nmcli device wifi list
nmcli device wifi connect "SSID" password "PASSWORD"
#+END_SRC

**** wifi.conf
#+BEGIN_SRC sh
network={
  ssid="ssid-name"
  key_mgmt=WPA-PSK
  psk="password"
}
#+END_SRC

Or for an open network:

#+BEGIN_SRC sh
network={
  ssid="ssid-name"
  key_mgmt=NONE
  priority=1
}
#+END_SRC

*** After Fist Install
To update the Guix Channels and pull the latest Guix and Channel Versions, run `guix pull`.
Then, to rebuild your system, run `sudo guix system reconfigure /path/to/config.scm`.
After running `guix pull`, remember to run `hash guix` to update bash's cache and clear it of the old guix binary location.
Also make sure that "~/.config/guix/channels.scm" or "/etc/guix/channels.scm" is the *first* item in your $PATH.

** Useful Commands
**** List System Generations
#+BEGIN_SRC sh
guix system list-generations
#+END_SRC
**** Describe System Generation
#+BEGIN_SRC sh
guix system describe
#+END_SRC
**** Delete Generations older than 1 Month
#+BEGIN_SRC sh
sudo guix system delete-generations 1m
#+END_SRC
**** Roll Back to Older Generation
#+BEGIN_SRC sh
sudo guix system roll-back
#+END_SRC
**** Guix Garbage Collector
Delete Generations older than 1 Month, and try to free up at least 10GiB.
#+BEGIN_SRC sh
guix gc -d 1m -F 10G
#+END_SRC
**** Deduplicate/Optimize Guix Store
#+BEGIN_SRC sh
guix gc --optimize
#+END_SRC
**** Reconfigure Guix Home
#+BEGIN_SRC sh
guix home reconfigure /path/to/home.scm
#+END_SRC
**** Describe/List Channels
#+BEGIN_SRC sh
guix describe
#+END_SRC
**** Upgrade Packages
#+BEGIN_SRC sh
guix upgrade
#+END_SRC
**** Reformat/Style Scheme File
This can help to find syntax errors, such as misplaced brackets, easier.
#+BEGIN_SRC sh
guix style -f config.scm
#+END_SRC
**** List Installed Packages
#+BEGIN_SRC sh
guix package --list-installed
#+END_SRC
**** Install Package
#+BEGIN_SRC sh
guix install
#+END_SRC
**** Remove Package
#+BEGIN_SRC sh
guix remove
#+END_SRC
**** Delete Old Package Generations
#+BEGIN_SRC sh
guix package --delete-generations
#+END_SRC

*** Shepherd Commands
**** Start Service
#+BEGIN_SRC sh
sudo herd start name
#+END_SRC
**** Stop Service
#+BEGIN_SRC sh
sudo herd stop name
#+END_SRC
**** Restart Service
#+BEGIN_SRC sh
sudo herd restart name
#+END_SRC
**** Service Status
#+BEGIN_SRC sh
sudo herd status name
#+END_SRC
**** List Services
#+BEGIN_SRC sh
sudo herd status
#+END_SRC
*** Combinations
**** Guix Garbage Collecting
1. `guix gc`
2. `sudo guix system delete-generations 1d`
3. `guix package --delete-generations`

**** Guix Pull and Daemon Restart
1. `guix pull`
2. `sudo systemctl restart guix-daemon.service` or `sudo herd restart guix-daemon`

** Snippets
*** Pin Kernel Version
Use this to pin nonguix & guix channel to linux kernel 6.18.7 commit, so that not every rebuild, rebuilds the entire kernel.
#+BEGIN_SRC emacs-lisp
(operating-system
  (kernel (let*
              ((channels
                (list (channel
                       (name 'nonguix)
                       (url "https://gitlab.com/nonguix/nonguix")
                       (commit "6c0ea215e0bd089bf3b2097e5c59dd726fbbe3045"))
                      (channel
                       (name 'guix)
                       (url "https://git.guix.gnu.org/guix.git")
                       (commit "9e6705676ffb7568d03b2b6c9fa3944afa2341e7"))))
               (inferior
                (inferior-for-channels channels)))
              (first (lookup-inferior-packages inferior "linux" "6.18.7"))))
)
#+END_SRC
*** Bootloader
**** Legacy/BIOS
#+BEGIN_SRC emacs-lisp
(bootloader (bootloader-configuration
             (keyboard-layout keyboard-layout)
             (bootloader grub-bootloader)
             (targets '("/dev/sda1"))))
#+END_SRC
**** (U)EFI
#+BEGIN_SRC emacs-lisp
(bootloader (bootloader-configuration
             (keyboard-layout keyboard-layout)
             (bootloader grub-efi-bootloader)
             (targets '("/boot/efi"))))
#+END_SRC
*** File-System
Create the root (/) partition with label "guix-root", and the boot partition (if present) with label "guix-efi" or "guix-boot".
Labels can be attached afterwards via 'sudo e2label /dev/sda1 guix-root' or 'sudo tune2fs -L guix-root /dev/sda1'.
**** Encrypted
#+BEGIN_SRC emacs-lisp
(file-systems (append
               (list (file-system
                      (device "/dev/mapper/cryptroot")
                      (mount-point "/")
                      (type "ext4")
                      (dependencies mapped-devices))
                     (file-system
                      (device (uuid "PARTITION_1_UUID" 'fat32))
                      (mount-point "/boot/efi")
                      (type "vfat")))
               %base-file-systems))
#+END_SRC
**** Regular (U)EFI
#+BEGIN_SRC emacs-lisp
(file-systems (cons* (file-system
                      (mount-point "/")
                      (device (file-system-label "guix-root"))
                      (type "ext4"))
                     (file-system
                      (mount-point "/boot/efi")
                      (device (file-system-label "guix-efi"))
                      ; or:
                      ;  (device (uuid "PartitionUUID"))
                      ; optional:
                      ;  (device (uuid "PartitionUUID" 'fat32))
                      (type "vfat"))
                     %base-file-systems))
#+END_SRC
**** Regular (Legacy/BIOS)
#+BEGIN_SRC emacs-lisp
(file-systems (cons* (file-system
                      (mount-point "/")
                      (device (file-system-label "guix-root"))
                      (type "ext4"))
                     %base-file-systems))
#+END_SRC
*** Nonguix Transformation
See Nonguix Documentation (https://gitlab.com/nonguix/nonguix), Section: NVIDIA Graphics Card -> System Setup.
**** Xorg
#+BEGIN_SRC emacs-lisp
((nonguix-transformation-nvidia #:configure-xorg? #t)
 %guix-os)
#+END_SRC
**** Wayland
#+BEGIN_SRC emacs-lisp
((compose (nonguix-transformation-nvidia))
 %guix-os)
#+END_SRC
*** Service Configuration
**** Delete Service
#+BEGIN_SRC emacs-lisp
(modify-services %desktop-services
 (delete pulseaudio-service-type)
)
#+END_SRC
**** Xorg Nvidia Service
#+BEGIN_SRC emacs-lisp
(services
 (append
  (list
   (set-xorg-configuration
    (xorg-configuration
     (keyboard-layout keyboard-layout)
     (modules (cons nvidia-driver %default-xorg-modules))
     (drivers '("nvidia"))))
  )
 )
)
#+END_SRC
*** Specify Package's Source Channel
To specify the channel a package should be pulled from, define the name like so:
#+BEGIN_SRC emacs-lisp
(use-modules (jonabron packages emacs) #:rename (emacs-fancy-dabbrev jonabron-emacs-fancy-dabbrev))
(use-modules (emacs packages melpa) #:rename (emacs-fancy-dabbrev melpa-emacs-fancy-dabbrev))
#+END_SRC

And then add the renamed package to the packages list:
#+BEGIN_SRC emacs-lisp
(home-environment
 (packages (specifications->packages
            (list "jonabron-emacs-fancy-dabbrev") ; or: "melpa-emacs-fancy-dabbrev"
 ))
)
#+END_SRC
** GNU Hurd
*** System Service Setup
#+BEGIN_SRC emacs-lisp
(services
 (append
  (list
   (service hurd-vm-service-type
            (hurd-vm-configuration
             (memory-size 2048)
             (secret-directory "/etc/guix/hurd-secrets")))
  )
 )
)
#+END_SRC
*** Entering
Enter Hurd via `ssh -p 2222 root@localhost`. (+`-X` for X11 passthrough)

*** File Transfer
Copy files to Hurd via `scp -P 2222 <file> root@localhost:~/`, and similarly, from Hurd, via `scp -P 2222 root@localhost:/hurd/path/to/file ./`.

*** SSH Setup
Generate SSH Key via `ssh-keygen -t ed25519`, spam enter to not set a passphrase and use the default settings, then copy the `~/.ssh/id_XXXXXXX.pub` key into `/etc/guix/hurd-secrets` before rebuilding the system.

*** Shepherd Service Commands
**** Hurd Status
`herd status hurd-vm`

**** Stop Hurd
`herd stop hurd-vm`

**** Start Hurd
`herd start hurd-vm`

*** Optional Fixes
**** X11 Forwarding
In case X11/Xorg forwarding via SSH does not work, it may be advised to set an option such as `xhost +local:root`.
